"""
CG4002 B02 - Step 3: Training Pipeline (7 Classes)
====================================================
Covers Task 5 demo requirements:
  - Segmentation: sliding window 128 samples @ 50Hz
  - Feature selection: raw 18-channel IMU (CNN learns features automatically)
  - Training: PyTorch, Adam optimizer, CrossEntropyLoss, 50 epochs
  - Libraries: PyTorch, NumPy, matplotlib
  - Saves: best model, final model, ONNX export, training curves, normalization params

Usage:
  cd cg4002-ai-demo
  python software/train.py
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import os
import time
import json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from tabulate import tabulate

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from model import ExerciseCNN

CLASSES = ["high_knees", "pushup", "situp", "lunge", "squat", "overhead_hold", "unknown"]

CONFIG = {
    "num_features": 12,         # ax, ay, az, avm from 3 sensors (arm, chest, thigh)
    "num_classes": 7,
    "window_size": 20,          # ~2.5s at 8Hz
    "batch_size": 32,
    "learning_rate": 0.001,
    "weight_decay": 1e-4,
    "epochs": 50,
    "optimizer": "Adam",
    "loss_function": "CrossEntropyLoss",
    "scheduler": "StepLR (step=20, gamma=0.5)",
    "framework": "PyTorch",
}


def load_data():
    """Load numpy arrays generated by Step 1."""
    X_tr = np.load("data/train/X.npy")
    y_tr = np.load("data/train/y.npy")
    X_va = np.load("data/val/X.npy")
    y_va = np.load("data/val/y.npy")
    print(f"  Train: X={X_tr.shape}  y={y_tr.shape}")
    print(f"  Val:   X={X_va.shape}  y={y_va.shape}")
    print(f"  (Test set in data/test/ is held out for evaluate.py only)")
    return X_tr, y_tr, X_va, y_va


def normalize(X_tr, X_va):
    """
    Z-score normalization per feature channel.
    Computed on training data only, applied to both.
    Saves params for deployment (needed on Ultra96 too).
    """
    flat = X_tr.reshape(-1, X_tr.shape[-1])
    mean = flat.mean(axis=0)
    std  = flat.std(axis=0)
    std[std < 1e-8] = 1.0   # prevent division by zero

    X_tr_norm = ((X_tr - mean) / std).astype(np.float32)
    X_va_norm = ((X_va - mean) / std).astype(np.float32)

    os.makedirs("models", exist_ok=True)
    np.save("models/norm_mean.npy", mean)
    np.save("models/norm_std.npy", std)
    print(f"  Normalization saved: mean shape={mean.shape}, std shape={std.shape}")

    return X_tr_norm, X_va_norm


def train_one_epoch(model, loader, criterion, optimizer):
    """Train for one epoch, return avg loss and accuracy."""
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * X_batch.size(0)
        correct += (outputs.argmax(dim=1) == y_batch).sum().item()
        total += y_batch.size(0)

    return total_loss / total, correct / total


def evaluate(model, loader, criterion):
    """Evaluate on a dataset, return avg loss and accuracy."""
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    with torch.no_grad():
        for X_batch, y_batch in loader:
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            total_loss += loss.item() * X_batch.size(0)
            correct += (outputs.argmax(dim=1) == y_batch).sum().item()
            total += y_batch.size(0)

    return total_loss / total, correct / total


def plot_curves(history, save_path):
    """Plot training/validation loss and accuracy curves."""
    epochs = range(1, len(history["train_loss"]) + 1)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(epochs, history["train_loss"], 'b-', linewidth=2, label='Train Loss')
    ax1.plot(epochs, history["val_loss"],   'r-', linewidth=2, label='Val Loss')
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('Training & Validation Loss', fontsize=14)
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)

    ax2.plot(epochs, history["train_acc"], 'b-', linewidth=2, label='Train Acc')
    ax2.plot(epochs, history["val_acc"],   'r-', linewidth=2, label='Val Acc')
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy', fontsize=12)
    ax2.set_title('Training & Validation Accuracy', fontsize=14)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 1.05])

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Training curves saved: {save_path}")


def main():
    print("=" * 65)
    print("  CG4002 B02 — Step 3: Training Pipeline")
    print("=" * 65)

    print("\n  Training Configuration:")
    print(tabulate(CONFIG.items(), headers=["Parameter", "Value"], tablefmt="simple"))

    print("\n  Loading data...")
    X_tr, y_tr, X_va, y_va = load_data()

    print("\n  Normalizing (Z-score per channel, fit on train only)...")
    X_tr, X_va = normalize(X_tr, X_va)

    train_ds = TensorDataset(torch.from_numpy(X_tr), torch.from_numpy(y_tr))
    val_ds   = TensorDataset(torch.from_numpy(X_va), torch.from_numpy(y_va))
    train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)
    test_loader  = DataLoader(val_ds,   batch_size=CONFIG["batch_size"], shuffle=False)

    print("\n  Creating model...")
    model = ExerciseCNN(num_features=CONFIG["num_features"], num_classes=CONFIG["num_classes"])
    print(f"  Parameters: {model.count_params():,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=CONFIG["learning_rate"],
                           weight_decay=CONFIG["weight_decay"])
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.5)

    print("\n  Training...")
    print("  " + "-" * 61)
    print(f"  {'Epoch':>6}  {'Train Loss':>11}  {'Train Acc':>10}  "
          f"{'Val Loss':>10}  {'Val Acc':>9}")
    print("  " + "-" * 61)

    history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}
    best_val_acc = 0.0
    start_time = time.time()

    for epoch in range(1, CONFIG["epochs"] + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer)
        va_loss, va_acc = evaluate(model, test_loader, criterion)
        scheduler.step()

        history["train_loss"].append(tr_loss)
        history["train_acc"].append(tr_acc)
        history["val_loss"].append(va_loss)
        history["val_acc"].append(va_acc)

        if epoch == 1 or epoch % 5 == 0 or epoch == CONFIG["epochs"]:
            print(f"  {epoch:>6}  {tr_loss:>11.4f}  {tr_acc:>10.4f}  "
                  f"{va_loss:>10.4f}  {va_acc:>9.4f}")

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            torch.save(model.state_dict(), "models/best_model.pth")

    elapsed = time.time() - start_time
    print("  " + "-" * 61)
    print(f"  Training complete in {elapsed:.1f}s")
    print(f"  Best validation accuracy: {best_val_acc:.4f} ({best_val_acc*100:.1f}%)")

    torch.save(model.state_dict(), "models/final_model.pth")
    print(f"\n  Models saved:")
    print(f"    models/best_model.pth   (best val acc)")
    print(f"    models/final_model.pth  (last epoch)")

    print("\n  Exporting to ONNX...")
    model.eval()
    dummy = torch.randn(1, CONFIG["window_size"], CONFIG["num_features"])
    torch.onnx.export(
        model, dummy, "models/exercise_cnn.onnx",
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}},
        opset_version=13,
    )
    print(f"    models/exercise_cnn.onnx")

    print("\n  Plotting training curves...")
    plot_curves(history, "models/training_curves.png")

    with open("models/training_history.json", "w") as f:
        json.dump(history, f, indent=2)
    with open("models/training_config.json", "w") as f:
        json.dump(CONFIG, f, indent=2)

    print("\n  Summary:")
    print(tabulate([
        ["Framework",     "PyTorch"],
        ["Optimizer",     f"Adam (lr={CONFIG['learning_rate']})"],
        ["Loss",          "CrossEntropyLoss"],
        ["Epochs",        CONFIG["epochs"]],
        ["Batch size",    CONFIG["batch_size"]],
        ["Segmentation",  f"Sliding window, {CONFIG['window_size']} @ 8Hz"],
        ["Features",      f"Raw {CONFIG['num_features']}-ch IMU (3 sensors x ax,ay,az,avm)"],
        ["Normalization", "Z-score per channel"],
        ["Best Val Acc",  f"{best_val_acc*100:.1f}%"],
        ["Training Time", f"{elapsed:.1f}s"],
    ], tablefmt="simple"))
    print()
    print("  ✓ Step 3 complete! All artifacts in models/")
    print("=" * 65)


if __name__ == "__main__":
    main()
