"""
CG4002 B02 - Training Pipeline (7 Classes)
==========================================
Trains ExerciseCNN on windowed IMU data produced by convert_real_data.py.

  - Input: (N, 20, 12) windows — 20 timesteps x 12 raw features at 8 Hz
  - Classes: high_knees, lunge, squat, overhead_arm, push_up, sit_up, unknown
  - Optimizer: Adam, CrossEntropyLoss, 50 epochs, StepLR decay
  - Outputs: best_model.pth, final_model.pth, exercise_cnn.onnx, norm params, training curves

Usage:
  python train.py
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import os
import time
import json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import sys
sys.path.insert(0, os.path.dirname(__file__))
from model import ExerciseCNN

CONFIG = {
    "num_features": None,  # set after data load
    "num_classes": 7,
    "window_size": 20,           # ~2.5s at 8 Hz
    "sample_rate": 8,
    "batch_size": 32,
    "learning_rate": 0.001,
    "weight_decay": 1e-4,
    "epochs": 50,
    "optimizer": "Adam",
    "loss_function": "CrossEntropyLoss",
    "scheduler": "StepLR (step=20, gamma=0.5)",
    "framework": "PyTorch",
    "training_data": "Real_Training_Data/Previous (5 people)",
}


def load_data():
    """Load numpy arrays generated by convert_real_data.py."""
    X_tr = np.load("data/train/X.npy")
    y_tr = np.load("data/train/y.npy")
    X_va = np.load("data/val/X.npy")
    y_va = np.load("data/val/y.npy")
    print(f"  Train: X={X_tr.shape}  y={y_tr.shape}")
    print(f"  Val:   X={X_va.shape}  y={y_va.shape}")
    print(f"  (Test set in data/test/ held out for evaluate.py)")
    return X_tr, y_tr, X_va, y_va


def normalize(X_tr, X_va):
    """
    Z-score normalization per feature channel, fit on training data only.
    Saves parameters for use at inference time on the Ultra96.
    """
    flat = X_tr.reshape(-1, X_tr.shape[-1])
    mean = flat.mean(axis=0)
    std  = flat.std(axis=0)
    std[std < 1e-8] = 1.0

    X_tr_norm = ((X_tr - mean) / std).astype(np.float32)
    X_va_norm = ((X_va - mean) / std).astype(np.float32)

    os.makedirs("models", exist_ok=True)
    np.save("models/norm_mean.npy", mean)
    np.save("models/norm_std.npy",  std)
    print(f"  Normalization saved: mean shape={mean.shape}")

    return X_tr_norm, X_va_norm


def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    total_loss, correct, total = 0.0, 0, 0
    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * X_batch.size(0)
        correct += (outputs.argmax(dim=1) == y_batch).sum().item()
        total   += y_batch.size(0)
    return total_loss / total, correct / total


def evaluate_model(model, loader, criterion):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for X_batch, y_batch in loader:
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            total_loss += loss.item() * X_batch.size(0)
            correct += (outputs.argmax(dim=1) == y_batch).sum().item()
            total   += y_batch.size(0)
    return total_loss / total, correct / total


def plot_curves(history, save_path):
    epochs = range(1, len(history["train_loss"]) + 1)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(epochs, history["train_loss"], 'b-', linewidth=2, label='Train')
    ax1.plot(epochs, history["val_loss"],   'r-', linewidth=2, label='Val')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.set_title('Training & Validation Loss')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(epochs, history["train_acc"], 'b-', linewidth=2, label='Train')
    ax2.plot(epochs, history["val_acc"],   'r-', linewidth=2, label='Val')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.set_title('Training & Validation Accuracy')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 1.05])

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Training curves saved: {save_path}")


def main():
    print("=" * 65)
    print("  CG4002 B02 - Training Pipeline")
    print("=" * 65)

    print("\n  Loading data...")
    X_tr, y_tr, X_va, y_va = load_data()
    CONFIG["num_features"] = X_tr.shape[-1]

    print("\n  Normalizing (Z-score per channel, fit on train only)...")
    X_tr, X_va = normalize(X_tr, X_va)

    train_loader = DataLoader(
        TensorDataset(torch.from_numpy(X_tr), torch.from_numpy(y_tr)),
        batch_size=CONFIG["batch_size"], shuffle=True
    )
    val_loader = DataLoader(
        TensorDataset(torch.from_numpy(X_va), torch.from_numpy(y_va)),
        batch_size=CONFIG["batch_size"], shuffle=False
    )

    print("\n  Creating model...")
    model = ExerciseCNN(num_features=CONFIG["num_features"], num_classes=CONFIG["num_classes"])
    pretrained_path = "models/pretrained_model.pth"
    if os.path.exists(pretrained_path):
        model.load_state_dict(torch.load(pretrained_path, map_location="cpu", weights_only=True))
        print(f"  Loaded pretrained weights from {pretrained_path}")
    else:
        print(f"  Training from scratch")
    print(f"  Parameters: {model.count_params():,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=CONFIG["learning_rate"],
                           weight_decay=CONFIG["weight_decay"])
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.5)

    print("\n  Training...")
    print(f"  {'Epoch':>6}  {'Train Loss':>11}  {'Train Acc':>10}  {'Val Loss':>10}  {'Val Acc':>9}")
    print("  " + "-" * 57)

    history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}
    best_val_acc = 0.0
    start_time = time.time()

    for epoch in range(1, CONFIG["epochs"] + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer)
        va_loss, va_acc = evaluate_model(model, val_loader, criterion)
        scheduler.step()

        history["train_loss"].append(tr_loss)
        history["train_acc"].append(tr_acc)
        history["val_loss"].append(va_loss)
        history["val_acc"].append(va_acc)

        if epoch == 1 or epoch % 5 == 0 or epoch == CONFIG["epochs"]:
            print(f"  {epoch:>6}  {tr_loss:>11.4f}  {tr_acc:>10.4f}  "
                  f"{va_loss:>10.4f}  {va_acc:>9.4f}")

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            torch.save(model.state_dict(), "models/best_model.pth")

    elapsed = time.time() - start_time
    print("  " + "-" * 57)
    print(f"  Training complete in {elapsed:.1f}s")
    print(f"  Best validation accuracy: {best_val_acc*100:.1f}%")

    torch.save(model.state_dict(), "models/final_model.pth")
    print(f"\n  Saved:")
    print(f"    models/best_model.pth")
    print(f"    models/final_model.pth")

    print("\n  Exporting to ONNX...")
    model.eval()
    dummy = torch.randn(1, CONFIG["window_size"], CONFIG["num_features"])
    torch.onnx.export(
        model, dummy, "models/exercise_cnn.onnx",
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}},
        opset_version=13,
    )
    print(f"    models/exercise_cnn.onnx")

    plot_curves(history, "models/training_curves.png")

    with open("models/training_history.json", "w") as f:
        json.dump(history, f, indent=2)
    with open("models/training_config.json", "w") as f:
        json.dump(CONFIG, f, indent=2)

    print(f"\n  Done! Best val acc: {best_val_acc*100:.1f}%")
    print("=" * 65)


if __name__ == "__main__":
    main()
